ARG NETBOX_BASE_IMAGE=docker.io/netboxcommunity/netbox:v4.6-5.0.2

FROM ${NETBOX_BASE_IMAGE}

USER root

COPY plugin_requirements.txt /opt/netbox/plugin_requirements.txt

RUN /usr/local/bin/uv pip install \
    --python /opt/netbox/venv/bin/python \
    -r /opt/netbox/plugin_requirements.txt

COPY configuration/plugins.py /etc/netbox/config/plugins.py

RUN DEBUG="true" \
    SECRET_KEY="dummydummydummydummydummydummydummydummydummydummy" \
    /opt/netbox/venv/bin/python \
    /opt/netbox/netbox/manage.py collectstatic \
    --no-input

USER netbox
